name: Update README

on:
  push:
    paths:
      - "learning_log.json" # 예시로 learning_log.json 파일에 대한 변경 사항을 감지

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # 기본 credentials 사용을 비활성화

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Update README
        run: node updateReadme.js

      - name: Configure Git
        run: |
          git config --global user.email "dnr8874@naver.com"
          git config --global user.name "wukdddang"

      - name: Commit and Push changes
        run: |
          git add README.md
          git commit -m "Automatically update README with learning log" -a || echo "No changes to commit"
          git push https://${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
